// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akeelnazir/osint-app/backend/internal/ent/activitylog"
	"github.com/akeelnazir/osint-app/backend/internal/ent/caserecord"
	"github.com/akeelnazir/osint-app/backend/internal/ent/predicate"
	"github.com/akeelnazir/osint-app/backend/internal/ent/user"
)

// ActivityLogUpdate is the builder for updating ActivityLog entities.
type ActivityLogUpdate struct {
	config
	hooks    []Hook
	mutation *ActivityLogMutation
}

// Where appends a list predicates to the ActivityLogUpdate builder.
func (_u *ActivityLogUpdate) Where(ps ...predicate.ActivityLog) *ActivityLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAction sets the "action" field.
func (_u *ActivityLogUpdate) SetAction(v string) *ActivityLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ActivityLogUpdate) SetNillableAction(v *string) *ActivityLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ActivityLogUpdate) SetTargetType(v string) *ActivityLogUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ActivityLogUpdate) SetNillableTargetType(v *string) *ActivityLogUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *ActivityLogUpdate) ClearTargetType() *ActivityLogUpdate {
	_u.mutation.ClearTargetType()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *ActivityLogUpdate) SetTargetID(v string) *ActivityLogUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *ActivityLogUpdate) SetNillableTargetID(v *string) *ActivityLogUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *ActivityLogUpdate) ClearTargetID() *ActivityLogUpdate {
	_u.mutation.ClearTargetID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ActivityLogUpdate) SetMetadata(v map[string]interface{}) *ActivityLogUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ActivityLogUpdate) ClearMetadata() *ActivityLogUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ActivityLogUpdate) SetUserID(id int) *ActivityLogUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *ActivityLogUpdate) SetNillableUserID(id *int) *ActivityLogUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ActivityLogUpdate) SetUser(v *User) *ActivityLogUpdate {
	return _u.SetUserID(v.ID)
}

// SetCaseID sets the "case" edge to the CaseRecord entity by ID.
func (_u *ActivityLogUpdate) SetCaseID(id int) *ActivityLogUpdate {
	_u.mutation.SetCaseID(id)
	return _u
}

// SetNillableCaseID sets the "case" edge to the CaseRecord entity by ID if the given value is not nil.
func (_u *ActivityLogUpdate) SetNillableCaseID(id *int) *ActivityLogUpdate {
	if id != nil {
		_u = _u.SetCaseID(*id)
	}
	return _u
}

// SetCase sets the "case" edge to the CaseRecord entity.
func (_u *ActivityLogUpdate) SetCase(v *CaseRecord) *ActivityLogUpdate {
	return _u.SetCaseID(v.ID)
}

// Mutation returns the ActivityLogMutation object of the builder.
func (_u *ActivityLogUpdate) Mutation() *ActivityLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ActivityLogUpdate) ClearUser() *ActivityLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearCase clears the "case" edge to the CaseRecord entity.
func (_u *ActivityLogUpdate) ClearCase() *ActivityLogUpdate {
	_u.mutation.ClearCase()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActivityLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActivityLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := activitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivityLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activitylog.Table, activitylog.Columns, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(activitylog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(activitylog.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(activitylog.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(activitylog.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(activitylog.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(activitylog.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(activitylog.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.CaseTable,
			Columns: []string{activitylog.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.CaseTable,
			Columns: []string{activitylog.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activitylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActivityLogUpdateOne is the builder for updating a single ActivityLog entity.
type ActivityLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivityLogMutation
}

// SetAction sets the "action" field.
func (_u *ActivityLogUpdateOne) SetAction(v string) *ActivityLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ActivityLogUpdateOne) SetNillableAction(v *string) *ActivityLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ActivityLogUpdateOne) SetTargetType(v string) *ActivityLogUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ActivityLogUpdateOne) SetNillableTargetType(v *string) *ActivityLogUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *ActivityLogUpdateOne) ClearTargetType() *ActivityLogUpdateOne {
	_u.mutation.ClearTargetType()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *ActivityLogUpdateOne) SetTargetID(v string) *ActivityLogUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *ActivityLogUpdateOne) SetNillableTargetID(v *string) *ActivityLogUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *ActivityLogUpdateOne) ClearTargetID() *ActivityLogUpdateOne {
	_u.mutation.ClearTargetID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ActivityLogUpdateOne) SetMetadata(v map[string]interface{}) *ActivityLogUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ActivityLogUpdateOne) ClearMetadata() *ActivityLogUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ActivityLogUpdateOne) SetUserID(id int) *ActivityLogUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *ActivityLogUpdateOne) SetNillableUserID(id *int) *ActivityLogUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ActivityLogUpdateOne) SetUser(v *User) *ActivityLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetCaseID sets the "case" edge to the CaseRecord entity by ID.
func (_u *ActivityLogUpdateOne) SetCaseID(id int) *ActivityLogUpdateOne {
	_u.mutation.SetCaseID(id)
	return _u
}

// SetNillableCaseID sets the "case" edge to the CaseRecord entity by ID if the given value is not nil.
func (_u *ActivityLogUpdateOne) SetNillableCaseID(id *int) *ActivityLogUpdateOne {
	if id != nil {
		_u = _u.SetCaseID(*id)
	}
	return _u
}

// SetCase sets the "case" edge to the CaseRecord entity.
func (_u *ActivityLogUpdateOne) SetCase(v *CaseRecord) *ActivityLogUpdateOne {
	return _u.SetCaseID(v.ID)
}

// Mutation returns the ActivityLogMutation object of the builder.
func (_u *ActivityLogUpdateOne) Mutation() *ActivityLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ActivityLogUpdateOne) ClearUser() *ActivityLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearCase clears the "case" edge to the CaseRecord entity.
func (_u *ActivityLogUpdateOne) ClearCase() *ActivityLogUpdateOne {
	_u.mutation.ClearCase()
	return _u
}

// Where appends a list predicates to the ActivityLogUpdate builder.
func (_u *ActivityLogUpdateOne) Where(ps ...predicate.ActivityLog) *ActivityLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActivityLogUpdateOne) Select(field string, fields ...string) *ActivityLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActivityLog entity.
func (_u *ActivityLogUpdateOne) Save(ctx context.Context) (*ActivityLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivityLogUpdateOne) SaveX(ctx context.Context) *ActivityLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActivityLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivityLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivityLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := activitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *ActivityLogUpdateOne) sqlSave(ctx context.Context) (_node *ActivityLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activitylog.Table, activitylog.Columns, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActivityLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activitylog.FieldID)
		for _, f := range fields {
			if !activitylog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activitylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(activitylog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(activitylog.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(activitylog.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(activitylog.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(activitylog.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(activitylog.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(activitylog.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.UserTable,
			Columns: []string{activitylog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.CaseTable,
			Columns: []string{activitylog.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.CaseTable,
			Columns: []string{activitylog.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActivityLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activitylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
