// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akeelnazir/osint-app/backend/internal/ent/activitylog"
	"github.com/akeelnazir/osint-app/backend/internal/ent/caserecord"
	"github.com/akeelnazir/osint-app/backend/internal/ent/user"
)

// ActivityLog is the model entity for the ActivityLog schema.
type ActivityLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType string `json:"target_type,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID string `json:"target_id,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActivityLogQuery when eager-loading is set.
	Edges                ActivityLogEdges `json:"edges"`
	case_record_activity *int
	user_activity        *int
	selectValues         sql.SelectValues
}

// ActivityLogEdges holds the relations/edges for other nodes in the graph.
type ActivityLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Case holds the value of the case edge.
	Case *CaseRecord `json:"case,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CaseOrErr returns the Case value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityLogEdges) CaseOrErr() (*CaseRecord, error) {
	if e.Case != nil {
		return e.Case, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: caserecord.Label}
	}
	return nil, &NotLoadedError{edge: "case"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActivityLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activitylog.FieldMetadata:
			values[i] = new([]byte)
		case activitylog.FieldID:
			values[i] = new(sql.NullInt64)
		case activitylog.FieldAction, activitylog.FieldTargetType, activitylog.FieldTargetID:
			values[i] = new(sql.NullString)
		case activitylog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case activitylog.ForeignKeys[0]: // case_record_activity
			values[i] = new(sql.NullInt64)
		case activitylog.ForeignKeys[1]: // user_activity
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActivityLog fields.
func (_m *ActivityLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activitylog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case activitylog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case activitylog.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case activitylog.FieldTargetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = value.String
			}
		case activitylog.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case activitylog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case activitylog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field case_record_activity", value)
			} else if value.Valid {
				_m.case_record_activity = new(int)
				*_m.case_record_activity = int(value.Int64)
			}
		case activitylog.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_activity", value)
			} else if value.Valid {
				_m.user_activity = new(int)
				*_m.user_activity = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActivityLog.
// This includes values selected through modifiers, order, etc.
func (_m *ActivityLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ActivityLog entity.
func (_m *ActivityLog) QueryUser() *UserQuery {
	return NewActivityLogClient(_m.config).QueryUser(_m)
}

// QueryCase queries the "case" edge of the ActivityLog entity.
func (_m *ActivityLog) QueryCase() *CaseRecordQuery {
	return NewActivityLogClient(_m.config).QueryCase(_m)
}

// Update returns a builder for updating this ActivityLog.
// Note that you need to call ActivityLog.Unwrap() before calling this method if this ActivityLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActivityLog) Update() *ActivityLogUpdateOne {
	return NewActivityLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActivityLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActivityLog) Unwrap() *ActivityLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActivityLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActivityLog) String() string {
	var builder strings.Builder
	builder.WriteString("ActivityLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(_m.TargetID)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ActivityLogs is a parsable slice of ActivityLog.
type ActivityLogs []*ActivityLog
