// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akeelnazir/osint-app/backend/internal/ent/activitylog"
	"github.com/akeelnazir/osint-app/backend/internal/ent/casemember"
	"github.com/akeelnazir/osint-app/backend/internal/ent/caserecord"
	"github.com/akeelnazir/osint-app/backend/internal/ent/comment"
	"github.com/akeelnazir/osint-app/backend/internal/ent/evidence"
	"github.com/akeelnazir/osint-app/backend/internal/ent/predicate"
	"github.com/akeelnazir/osint-app/backend/internal/ent/tag"
	"github.com/akeelnazir/osint-app/backend/internal/ent/user"
)

// CaseRecordQuery is the builder for querying CaseRecord entities.
type CaseRecordQuery struct {
	config
	ctx          *QueryContext
	order        []caserecord.OrderOption
	inters       []Interceptor
	predicates   []predicate.CaseRecord
	withOwner    *UserQuery
	withMembers  *CaseMemberQuery
	withEvidence *EvidenceQuery
	withComments *CommentQuery
	withTags     *TagQuery
	withActivity *ActivityLogQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CaseRecordQuery builder.
func (_q *CaseRecordQuery) Where(ps ...predicate.CaseRecord) *CaseRecordQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CaseRecordQuery) Limit(limit int) *CaseRecordQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CaseRecordQuery) Offset(offset int) *CaseRecordQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CaseRecordQuery) Unique(unique bool) *CaseRecordQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CaseRecordQuery) Order(o ...caserecord.OrderOption) *CaseRecordQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *CaseRecordQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(caserecord.Table, caserecord.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, caserecord.OwnerTable, caserecord.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMembers chains the current query on the "members" edge.
func (_q *CaseRecordQuery) QueryMembers() *CaseMemberQuery {
	query := (&CaseMemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(caserecord.Table, caserecord.FieldID, selector),
			sqlgraph.To(casemember.Table, casemember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, caserecord.MembersTable, caserecord.MembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvidence chains the current query on the "evidence" edge.
func (_q *CaseRecordQuery) QueryEvidence() *EvidenceQuery {
	query := (&EvidenceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(caserecord.Table, caserecord.FieldID, selector),
			sqlgraph.To(evidence.Table, evidence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, caserecord.EvidenceTable, caserecord.EvidenceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryComments chains the current query on the "comments" edge.
func (_q *CaseRecordQuery) QueryComments() *CommentQuery {
	query := (&CommentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(caserecord.Table, caserecord.FieldID, selector),
			sqlgraph.To(comment.Table, comment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, caserecord.CommentsTable, caserecord.CommentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTags chains the current query on the "tags" edge.
func (_q *CaseRecordQuery) QueryTags() *TagQuery {
	query := (&TagClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(caserecord.Table, caserecord.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, caserecord.TagsTable, caserecord.TagsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryActivity chains the current query on the "activity" edge.
func (_q *CaseRecordQuery) QueryActivity() *ActivityLogQuery {
	query := (&ActivityLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(caserecord.Table, caserecord.FieldID, selector),
			sqlgraph.To(activitylog.Table, activitylog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, caserecord.ActivityTable, caserecord.ActivityColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CaseRecord entity from the query.
// Returns a *NotFoundError when no CaseRecord was found.
func (_q *CaseRecordQuery) First(ctx context.Context) (*CaseRecord, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{caserecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CaseRecordQuery) FirstX(ctx context.Context) *CaseRecord {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CaseRecord ID from the query.
// Returns a *NotFoundError when no CaseRecord ID was found.
func (_q *CaseRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{caserecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CaseRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CaseRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CaseRecord entity is found.
// Returns a *NotFoundError when no CaseRecord entities are found.
func (_q *CaseRecordQuery) Only(ctx context.Context) (*CaseRecord, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{caserecord.Label}
	default:
		return nil, &NotSingularError{caserecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CaseRecordQuery) OnlyX(ctx context.Context) *CaseRecord {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CaseRecord ID in the query.
// Returns a *NotSingularError when more than one CaseRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CaseRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{caserecord.Label}
	default:
		err = &NotSingularError{caserecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CaseRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CaseRecords.
func (_q *CaseRecordQuery) All(ctx context.Context) ([]*CaseRecord, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CaseRecord, *CaseRecordQuery]()
	return withInterceptors[[]*CaseRecord](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CaseRecordQuery) AllX(ctx context.Context) []*CaseRecord {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CaseRecord IDs.
func (_q *CaseRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(caserecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CaseRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CaseRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CaseRecordQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CaseRecordQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CaseRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CaseRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CaseRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CaseRecordQuery) Clone() *CaseRecordQuery {
	if _q == nil {
		return nil
	}
	return &CaseRecordQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]caserecord.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.CaseRecord{}, _q.predicates...),
		withOwner:    _q.withOwner.Clone(),
		withMembers:  _q.withMembers.Clone(),
		withEvidence: _q.withEvidence.Clone(),
		withComments: _q.withComments.Clone(),
		withTags:     _q.withTags.Clone(),
		withActivity: _q.withActivity.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CaseRecordQuery) WithOwner(opts ...func(*UserQuery)) *CaseRecordQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithMembers tells the query-builder to eager-load the nodes that are connected to
// the "members" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CaseRecordQuery) WithMembers(opts ...func(*CaseMemberQuery)) *CaseRecordQuery {
	query := (&CaseMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMembers = query
	return _q
}

// WithEvidence tells the query-builder to eager-load the nodes that are connected to
// the "evidence" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CaseRecordQuery) WithEvidence(opts ...func(*EvidenceQuery)) *CaseRecordQuery {
	query := (&EvidenceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvidence = query
	return _q
}

// WithComments tells the query-builder to eager-load the nodes that are connected to
// the "comments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CaseRecordQuery) WithComments(opts ...func(*CommentQuery)) *CaseRecordQuery {
	query := (&CommentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withComments = query
	return _q
}

// WithTags tells the query-builder to eager-load the nodes that are connected to
// the "tags" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CaseRecordQuery) WithTags(opts ...func(*TagQuery)) *CaseRecordQuery {
	query := (&TagClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTags = query
	return _q
}

// WithActivity tells the query-builder to eager-load the nodes that are connected to
// the "activity" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CaseRecordQuery) WithActivity(opts ...func(*ActivityLogQuery)) *CaseRecordQuery {
	query := (&ActivityLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withActivity = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CaseRecord.Query().
//		GroupBy(caserecord.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CaseRecordQuery) GroupBy(field string, fields ...string) *CaseRecordGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CaseRecordGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = caserecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.CaseRecord.Query().
//		Select(caserecord.FieldTitle).
//		Scan(ctx, &v)
func (_q *CaseRecordQuery) Select(fields ...string) *CaseRecordSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CaseRecordSelect{CaseRecordQuery: _q}
	sbuild.label = caserecord.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CaseRecordSelect configured with the given aggregations.
func (_q *CaseRecordQuery) Aggregate(fns ...AggregateFunc) *CaseRecordSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CaseRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !caserecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CaseRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CaseRecord, error) {
	var (
		nodes       = []*CaseRecord{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withOwner != nil,
			_q.withMembers != nil,
			_q.withEvidence != nil,
			_q.withComments != nil,
			_q.withTags != nil,
			_q.withActivity != nil,
		}
	)
	if _q.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, caserecord.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CaseRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CaseRecord{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *CaseRecord, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMembers; query != nil {
		if err := _q.loadMembers(ctx, query, nodes,
			func(n *CaseRecord) { n.Edges.Members = []*CaseMember{} },
			func(n *CaseRecord, e *CaseMember) { n.Edges.Members = append(n.Edges.Members, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvidence; query != nil {
		if err := _q.loadEvidence(ctx, query, nodes,
			func(n *CaseRecord) { n.Edges.Evidence = []*Evidence{} },
			func(n *CaseRecord, e *Evidence) { n.Edges.Evidence = append(n.Edges.Evidence, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withComments; query != nil {
		if err := _q.loadComments(ctx, query, nodes,
			func(n *CaseRecord) { n.Edges.Comments = []*Comment{} },
			func(n *CaseRecord, e *Comment) { n.Edges.Comments = append(n.Edges.Comments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTags; query != nil {
		if err := _q.loadTags(ctx, query, nodes,
			func(n *CaseRecord) { n.Edges.Tags = []*Tag{} },
			func(n *CaseRecord, e *Tag) { n.Edges.Tags = append(n.Edges.Tags, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withActivity; query != nil {
		if err := _q.loadActivity(ctx, query, nodes,
			func(n *CaseRecord) { n.Edges.Activity = []*ActivityLog{} },
			func(n *CaseRecord, e *ActivityLog) { n.Edges.Activity = append(n.Edges.Activity, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CaseRecordQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*CaseRecord, init func(*CaseRecord), assign func(*CaseRecord, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CaseRecord)
	for i := range nodes {
		if nodes[i].user_owned_cases == nil {
			continue
		}
		fk := *nodes[i].user_owned_cases
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_owned_cases" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CaseRecordQuery) loadMembers(ctx context.Context, query *CaseMemberQuery, nodes []*CaseRecord, init func(*CaseRecord), assign func(*CaseRecord, *CaseMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CaseRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CaseMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(caserecord.MembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.case_record_members
		if fk == nil {
			return fmt.Errorf(`foreign-key "case_record_members" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "case_record_members" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CaseRecordQuery) loadEvidence(ctx context.Context, query *EvidenceQuery, nodes []*CaseRecord, init func(*CaseRecord), assign func(*CaseRecord, *Evidence)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CaseRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Evidence(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(caserecord.EvidenceColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.case_record_evidence
		if fk == nil {
			return fmt.Errorf(`foreign-key "case_record_evidence" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "case_record_evidence" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CaseRecordQuery) loadComments(ctx context.Context, query *CommentQuery, nodes []*CaseRecord, init func(*CaseRecord), assign func(*CaseRecord, *Comment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CaseRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Comment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(caserecord.CommentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.case_record_comments
		if fk == nil {
			return fmt.Errorf(`foreign-key "case_record_comments" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "case_record_comments" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CaseRecordQuery) loadTags(ctx context.Context, query *TagQuery, nodes []*CaseRecord, init func(*CaseRecord), assign func(*CaseRecord, *Tag)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*CaseRecord)
	nids := make(map[int]map[*CaseRecord]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(caserecord.TagsTable)
		s.Join(joinT).On(s.C(tag.FieldID), joinT.C(caserecord.TagsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(caserecord.TagsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(caserecord.TagsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*CaseRecord]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Tag](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tags" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *CaseRecordQuery) loadActivity(ctx context.Context, query *ActivityLogQuery, nodes []*CaseRecord, init func(*CaseRecord), assign func(*CaseRecord, *ActivityLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CaseRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ActivityLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(caserecord.ActivityColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.case_record_activity
		if fk == nil {
			return fmt.Errorf(`foreign-key "case_record_activity" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "case_record_activity" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CaseRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CaseRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(caserecord.Table, caserecord.Columns, sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, caserecord.FieldID)
		for i := range fields {
			if fields[i] != caserecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CaseRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(caserecord.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = caserecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CaseRecordGroupBy is the group-by builder for CaseRecord entities.
type CaseRecordGroupBy struct {
	selector
	build *CaseRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CaseRecordGroupBy) Aggregate(fns ...AggregateFunc) *CaseRecordGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CaseRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaseRecordQuery, *CaseRecordGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CaseRecordGroupBy) sqlScan(ctx context.Context, root *CaseRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CaseRecordSelect is the builder for selecting fields of CaseRecord entities.
type CaseRecordSelect struct {
	*CaseRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CaseRecordSelect) Aggregate(fns ...AggregateFunc) *CaseRecordSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CaseRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CaseRecordQuery, *CaseRecordSelect](ctx, _s.CaseRecordQuery, _s, _s.inters, v)
}

func (_s *CaseRecordSelect) sqlScan(ctx context.Context, root *CaseRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
