// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akeelnazir/osint-app/backend/internal/ent/caserecord"
	"github.com/akeelnazir/osint-app/backend/internal/ent/comment"
	"github.com/akeelnazir/osint-app/backend/internal/ent/evidence"
	"github.com/akeelnazir/osint-app/backend/internal/ent/user"
)

// Comment is the model entity for the Comment schema.
type Comment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Mentions holds the value of the "mentions" field.
	Mentions []string `json:"mentions,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CommentQuery when eager-loading is set.
	Edges                CommentEdges `json:"edges"`
	case_record_comments *int
	evidence_comments    *int
	user_comments        *int
	selectValues         sql.SelectValues
}

// CommentEdges holds the relations/edges for other nodes in the graph.
type CommentEdges struct {
	// Author holds the value of the author edge.
	Author *User `json:"author,omitempty"`
	// Case holds the value of the case edge.
	Case *CaseRecord `json:"case,omitempty"`
	// Evidence holds the value of the evidence edge.
	Evidence *Evidence `json:"evidence,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommentEdges) AuthorOrErr() (*User, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// CaseOrErr returns the Case value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommentEdges) CaseOrErr() (*CaseRecord, error) {
	if e.Case != nil {
		return e.Case, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: caserecord.Label}
	}
	return nil, &NotLoadedError{edge: "case"}
}

// EvidenceOrErr returns the Evidence value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommentEdges) EvidenceOrErr() (*Evidence, error) {
	if e.Evidence != nil {
		return e.Evidence, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: evidence.Label}
	}
	return nil, &NotLoadedError{edge: "evidence"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Comment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case comment.FieldMentions:
			values[i] = new([]byte)
		case comment.FieldID:
			values[i] = new(sql.NullInt64)
		case comment.FieldBody:
			values[i] = new(sql.NullString)
		case comment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case comment.ForeignKeys[0]: // case_record_comments
			values[i] = new(sql.NullInt64)
		case comment.ForeignKeys[1]: // evidence_comments
			values[i] = new(sql.NullInt64)
		case comment.ForeignKeys[2]: // user_comments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Comment fields.
func (_m *Comment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case comment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case comment.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case comment.FieldMentions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mentions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Mentions); err != nil {
					return fmt.Errorf("unmarshal field mentions: %w", err)
				}
			}
		case comment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case comment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field case_record_comments", value)
			} else if value.Valid {
				_m.case_record_comments = new(int)
				*_m.case_record_comments = int(value.Int64)
			}
		case comment.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field evidence_comments", value)
			} else if value.Valid {
				_m.evidence_comments = new(int)
				*_m.evidence_comments = int(value.Int64)
			}
		case comment.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_comments", value)
			} else if value.Valid {
				_m.user_comments = new(int)
				*_m.user_comments = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Comment.
// This includes values selected through modifiers, order, etc.
func (_m *Comment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAuthor queries the "author" edge of the Comment entity.
func (_m *Comment) QueryAuthor() *UserQuery {
	return NewCommentClient(_m.config).QueryAuthor(_m)
}

// QueryCase queries the "case" edge of the Comment entity.
func (_m *Comment) QueryCase() *CaseRecordQuery {
	return NewCommentClient(_m.config).QueryCase(_m)
}

// QueryEvidence queries the "evidence" edge of the Comment entity.
func (_m *Comment) QueryEvidence() *EvidenceQuery {
	return NewCommentClient(_m.config).QueryEvidence(_m)
}

// Update returns a builder for updating this Comment.
// Note that you need to call Comment.Unwrap() before calling this method if this Comment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Comment) Update() *CommentUpdateOne {
	return NewCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Comment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Comment) Unwrap() *Comment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Comment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Comment) String() string {
	var builder strings.Builder
	builder.WriteString("Comment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("mentions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mentions))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Comments is a parsable slice of Comment.
type Comments []*Comment
