// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/akeelnazir/osint-app/backend/internal/ent/caserecord"
	"github.com/akeelnazir/osint-app/backend/internal/ent/comment"
	"github.com/akeelnazir/osint-app/backend/internal/ent/evidence"
	"github.com/akeelnazir/osint-app/backend/internal/ent/predicate"
	"github.com/akeelnazir/osint-app/backend/internal/ent/user"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBody sets the "body" field.
func (_u *CommentUpdate) SetBody(v string) *CommentUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableBody(v *string) *CommentUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetMentions sets the "mentions" field.
func (_u *CommentUpdate) SetMentions(v []string) *CommentUpdate {
	_u.mutation.SetMentions(v)
	return _u
}

// AppendMentions appends value to the "mentions" field.
func (_u *CommentUpdate) AppendMentions(v []string) *CommentUpdate {
	_u.mutation.AppendMentions(v)
	return _u
}

// ClearMentions clears the value of the "mentions" field.
func (_u *CommentUpdate) ClearMentions() *CommentUpdate {
	_u.mutation.ClearMentions()
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *CommentUpdate) SetAuthorID(id int) *CommentUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *CommentUpdate) SetAuthor(v *User) *CommentUpdate {
	return _u.SetAuthorID(v.ID)
}

// SetCaseID sets the "case" edge to the CaseRecord entity by ID.
func (_u *CommentUpdate) SetCaseID(id int) *CommentUpdate {
	_u.mutation.SetCaseID(id)
	return _u
}

// SetNillableCaseID sets the "case" edge to the CaseRecord entity by ID if the given value is not nil.
func (_u *CommentUpdate) SetNillableCaseID(id *int) *CommentUpdate {
	if id != nil {
		_u = _u.SetCaseID(*id)
	}
	return _u
}

// SetCase sets the "case" edge to the CaseRecord entity.
func (_u *CommentUpdate) SetCase(v *CaseRecord) *CommentUpdate {
	return _u.SetCaseID(v.ID)
}

// SetEvidenceID sets the "evidence" edge to the Evidence entity by ID.
func (_u *CommentUpdate) SetEvidenceID(id int) *CommentUpdate {
	_u.mutation.SetEvidenceID(id)
	return _u
}

// SetNillableEvidenceID sets the "evidence" edge to the Evidence entity by ID if the given value is not nil.
func (_u *CommentUpdate) SetNillableEvidenceID(id *int) *CommentUpdate {
	if id != nil {
		_u = _u.SetEvidenceID(*id)
	}
	return _u
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_u *CommentUpdate) SetEvidence(v *Evidence) *CommentUpdate {
	return _u.SetEvidenceID(v.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdate) Mutation() *CommentMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *CommentUpdate) ClearAuthor() *CommentUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCase clears the "case" edge to the CaseRecord entity.
func (_u *CommentUpdate) ClearCase() *CommentUpdate {
	_u.mutation.ClearCase()
	return _u
}

// ClearEvidence clears the "evidence" edge to the Evidence entity.
func (_u *CommentUpdate) ClearEvidence() *CommentUpdate {
	_u.mutation.ClearEvidence()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdate) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := comment.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Comment.body": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.author"`)
	}
	return nil
}

func (_u *CommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(comment.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mentions(); ok {
		_spec.SetField(comment.FieldMentions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMentions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, comment.FieldMentions, value)
		})
	}
	if _u.mutation.MentionsCleared() {
		_spec.ClearField(comment.FieldMentions, field.TypeJSON)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.CaseTable,
			Columns: []string{comment.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.CaseTable,
			Columns: []string{comment.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.EvidenceTable,
			Columns: []string{comment.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.EvidenceTable,
			Columns: []string{comment.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetBody sets the "body" field.
func (_u *CommentUpdateOne) SetBody(v string) *CommentUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableBody(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetMentions sets the "mentions" field.
func (_u *CommentUpdateOne) SetMentions(v []string) *CommentUpdateOne {
	_u.mutation.SetMentions(v)
	return _u
}

// AppendMentions appends value to the "mentions" field.
func (_u *CommentUpdateOne) AppendMentions(v []string) *CommentUpdateOne {
	_u.mutation.AppendMentions(v)
	return _u
}

// ClearMentions clears the value of the "mentions" field.
func (_u *CommentUpdateOne) ClearMentions() *CommentUpdateOne {
	_u.mutation.ClearMentions()
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *CommentUpdateOne) SetAuthorID(id int) *CommentUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *CommentUpdateOne) SetAuthor(v *User) *CommentUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// SetCaseID sets the "case" edge to the CaseRecord entity by ID.
func (_u *CommentUpdateOne) SetCaseID(id int) *CommentUpdateOne {
	_u.mutation.SetCaseID(id)
	return _u
}

// SetNillableCaseID sets the "case" edge to the CaseRecord entity by ID if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCaseID(id *int) *CommentUpdateOne {
	if id != nil {
		_u = _u.SetCaseID(*id)
	}
	return _u
}

// SetCase sets the "case" edge to the CaseRecord entity.
func (_u *CommentUpdateOne) SetCase(v *CaseRecord) *CommentUpdateOne {
	return _u.SetCaseID(v.ID)
}

// SetEvidenceID sets the "evidence" edge to the Evidence entity by ID.
func (_u *CommentUpdateOne) SetEvidenceID(id int) *CommentUpdateOne {
	_u.mutation.SetEvidenceID(id)
	return _u
}

// SetNillableEvidenceID sets the "evidence" edge to the Evidence entity by ID if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableEvidenceID(id *int) *CommentUpdateOne {
	if id != nil {
		_u = _u.SetEvidenceID(*id)
	}
	return _u
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_u *CommentUpdateOne) SetEvidence(v *Evidence) *CommentUpdateOne {
	return _u.SetEvidenceID(v.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdateOne) Mutation() *CommentMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *CommentUpdateOne) ClearAuthor() *CommentUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCase clears the "case" edge to the CaseRecord entity.
func (_u *CommentUpdateOne) ClearCase() *CommentUpdateOne {
	_u.mutation.ClearCase()
	return _u
}

// ClearEvidence clears the "evidence" edge to the Evidence entity.
func (_u *CommentUpdateOne) ClearEvidence() *CommentUpdateOne {
	_u.mutation.ClearEvidence()
	return _u
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Comment entity.
func (_u *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdateOne) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := comment.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Comment.body": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.author"`)
	}
	return nil
}

func (_u *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(comment.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mentions(); ok {
		_spec.SetField(comment.FieldMentions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMentions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, comment.FieldMentions, value)
		})
	}
	if _u.mutation.MentionsCleared() {
		_spec.ClearField(comment.FieldMentions, field.TypeJSON)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AuthorTable,
			Columns: []string{comment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.CaseTable,
			Columns: []string{comment.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.CaseTable,
			Columns: []string{comment.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caserecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.EvidenceTable,
			Columns: []string{comment.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.EvidenceTable,
			Columns: []string{comment.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Comment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
