// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akeelnazir/osint-app/backend/internal/ent/entity"
	"github.com/akeelnazir/osint-app/backend/internal/ent/evidence"
)

// EntityCreate is the builder for creating a Entity entity.
type EntityCreate struct {
	config
	mutation *EntityMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *EntityCreate) SetType(v entity.Type) *EntityCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *EntityCreate) SetValue(v string) *EntityCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *EntityCreate) SetConfidence(v float64) *EntityCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *EntityCreate) SetNillableConfidence(v *float64) *EntityCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntityCreate) SetCreatedAt(v time.Time) *EntityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntityCreate) SetNillableCreatedAt(v *time.Time) *EntityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEvidenceID sets the "evidence" edge to the Evidence entity by ID.
func (_c *EntityCreate) SetEvidenceID(id int) *EntityCreate {
	_c.mutation.SetEvidenceID(id)
	return _c
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_c *EntityCreate) SetEvidence(v *Evidence) *EntityCreate {
	return _c.SetEvidenceID(v.ID)
}

// Mutation returns the EntityMutation object of the builder.
func (_c *EntityCreate) Mutation() *EntityMutation {
	return _c.mutation
}

// Save creates the Entity in the database.
func (_c *EntityCreate) Save(ctx context.Context) (*Entity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityCreate) SaveX(ctx context.Context) *Entity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntityCreate) defaults() {
	if _, ok := _c.mutation.Confidence(); !ok {
		v := entity.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Entity.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := entity.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Entity.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Entity.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := entity.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Entity.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "Entity.confidence"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Entity.created_at"`)}
	}
	if len(_c.mutation.EvidenceIDs()) == 0 {
		return &ValidationError{Name: "evidence", err: errors.New(`ent: missing required edge "Entity.evidence"`)}
	}
	return nil
}

func (_c *EntityCreate) sqlSave(ctx context.Context) (*Entity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityCreate) createSpec() (*Entity, *sqlgraph.CreateSpec) {
	var (
		_node = &Entity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entity.Table, sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(entity.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(entity.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(entity.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entity.EvidenceTable,
			Columns: []string{entity.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.evidence_entities = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntityCreateBulk is the builder for creating many Entity entities in bulk.
type EntityCreateBulk struct {
	config
	err      error
	builders []*EntityCreate
}

// Save creates the Entity entities in the database.
func (_c *EntityCreateBulk) Save(ctx context.Context) ([]*Entity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Entity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityCreateBulk) SaveX(ctx context.Context) []*Entity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
