// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akeelnazir/osint-app/backend/internal/ent/entity"
	"github.com/akeelnazir/osint-app/backend/internal/ent/evidence"
	"github.com/akeelnazir/osint-app/backend/internal/ent/predicate"
)

// EntityUpdate is the builder for updating Entity entities.
type EntityUpdate struct {
	config
	hooks    []Hook
	mutation *EntityMutation
}

// Where appends a list predicates to the EntityUpdate builder.
func (_u *EntityUpdate) Where(ps ...predicate.Entity) *EntityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *EntityUpdate) SetType(v entity.Type) *EntityUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EntityUpdate) SetNillableType(v *entity.Type) *EntityUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EntityUpdate) SetValue(v string) *EntityUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EntityUpdate) SetNillableValue(v *string) *EntityUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *EntityUpdate) SetConfidence(v float64) *EntityUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *EntityUpdate) SetNillableConfidence(v *float64) *EntityUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *EntityUpdate) AddConfidence(v float64) *EntityUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetEvidenceID sets the "evidence" edge to the Evidence entity by ID.
func (_u *EntityUpdate) SetEvidenceID(id int) *EntityUpdate {
	_u.mutation.SetEvidenceID(id)
	return _u
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_u *EntityUpdate) SetEvidence(v *Evidence) *EntityUpdate {
	return _u.SetEvidenceID(v.ID)
}

// Mutation returns the EntityMutation object of the builder.
func (_u *EntityUpdate) Mutation() *EntityMutation {
	return _u.mutation
}

// ClearEvidence clears the "evidence" edge to the Evidence entity.
func (_u *EntityUpdate) ClearEvidence() *EntityUpdate {
	_u.mutation.ClearEvidence()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := entity.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Entity.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := entity.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Entity.value": %w`, err)}
		}
	}
	if _u.mutation.EvidenceCleared() && len(_u.mutation.EvidenceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entity.evidence"`)
	}
	return nil
}

func (_u *EntityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entity.Table, entity.Columns, sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(entity.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(entity.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(entity.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(entity.FieldConfidence, field.TypeFloat64, value)
	}
	if _u.mutation.EvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entity.EvidenceTable,
			Columns: []string{entity.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entity.EvidenceTable,
			Columns: []string{entity.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntityUpdateOne is the builder for updating a single Entity entity.
type EntityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityMutation
}

// SetType sets the "type" field.
func (_u *EntityUpdateOne) SetType(v entity.Type) *EntityUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *EntityUpdateOne) SetNillableType(v *entity.Type) *EntityUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EntityUpdateOne) SetValue(v string) *EntityUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EntityUpdateOne) SetNillableValue(v *string) *EntityUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *EntityUpdateOne) SetConfidence(v float64) *EntityUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *EntityUpdateOne) SetNillableConfidence(v *float64) *EntityUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *EntityUpdateOne) AddConfidence(v float64) *EntityUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetEvidenceID sets the "evidence" edge to the Evidence entity by ID.
func (_u *EntityUpdateOne) SetEvidenceID(id int) *EntityUpdateOne {
	_u.mutation.SetEvidenceID(id)
	return _u
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_u *EntityUpdateOne) SetEvidence(v *Evidence) *EntityUpdateOne {
	return _u.SetEvidenceID(v.ID)
}

// Mutation returns the EntityMutation object of the builder.
func (_u *EntityUpdateOne) Mutation() *EntityMutation {
	return _u.mutation
}

// ClearEvidence clears the "evidence" edge to the Evidence entity.
func (_u *EntityUpdateOne) ClearEvidence() *EntityUpdateOne {
	_u.mutation.ClearEvidence()
	return _u
}

// Where appends a list predicates to the EntityUpdate builder.
func (_u *EntityUpdateOne) Where(ps ...predicate.Entity) *EntityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntityUpdateOne) Select(field string, fields ...string) *EntityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Entity entity.
func (_u *EntityUpdateOne) Save(ctx context.Context) (*Entity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityUpdateOne) SaveX(ctx context.Context) *Entity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := entity.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Entity.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := entity.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Entity.value": %w`, err)}
		}
	}
	if _u.mutation.EvidenceCleared() && len(_u.mutation.EvidenceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entity.evidence"`)
	}
	return nil
}

func (_u *EntityUpdateOne) sqlSave(ctx context.Context) (_node *Entity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entity.Table, entity.Columns, sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entity.FieldID)
		for _, f := range fields {
			if !entity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(entity.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(entity.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(entity.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(entity.FieldConfidence, field.TypeFloat64, value)
	}
	if _u.mutation.EvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entity.EvidenceTable,
			Columns: []string{entity.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entity.EvidenceTable,
			Columns: []string{entity.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Entity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
