// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/akeelnazir/osint-app/backend/internal/ent/activitylog"
	"github.com/akeelnazir/osint-app/backend/internal/ent/casemember"
	"github.com/akeelnazir/osint-app/backend/internal/ent/caserecord"
	"github.com/akeelnazir/osint-app/backend/internal/ent/comment"
	"github.com/akeelnazir/osint-app/backend/internal/ent/entity"
	"github.com/akeelnazir/osint-app/backend/internal/ent/evidence"
	"github.com/akeelnazir/osint-app/backend/internal/ent/schema"
	"github.com/akeelnazir/osint-app/backend/internal/ent/tag"
	"github.com/akeelnazir/osint-app/backend/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activitylogFields := schema.ActivityLog{}.Fields()
	_ = activitylogFields
	// activitylogDescAction is the schema descriptor for action field.
	activitylogDescAction := activitylogFields[0].Descriptor()
	// activitylog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	activitylog.ActionValidator = activitylogDescAction.Validators[0].(func(string) error)
	// activitylogDescCreatedAt is the schema descriptor for created_at field.
	activitylogDescCreatedAt := activitylogFields[4].Descriptor()
	// activitylog.DefaultCreatedAt holds the default value on creation for the created_at field.
	activitylog.DefaultCreatedAt = activitylogDescCreatedAt.Default.(func() time.Time)
	casememberFields := schema.CaseMember{}.Fields()
	_ = casememberFields
	// casememberDescCreatedAt is the schema descriptor for created_at field.
	casememberDescCreatedAt := casememberFields[1].Descriptor()
	// casemember.DefaultCreatedAt holds the default value on creation for the created_at field.
	casemember.DefaultCreatedAt = casememberDescCreatedAt.Default.(func() time.Time)
	caserecordFields := schema.CaseRecord{}.Fields()
	_ = caserecordFields
	// caserecordDescTitle is the schema descriptor for title field.
	caserecordDescTitle := caserecordFields[0].Descriptor()
	// caserecord.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	caserecord.TitleValidator = caserecordDescTitle.Validators[0].(func(string) error)
	// caserecordDescCreatedAt is the schema descriptor for created_at field.
	caserecordDescCreatedAt := caserecordFields[4].Descriptor()
	// caserecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	caserecord.DefaultCreatedAt = caserecordDescCreatedAt.Default.(func() time.Time)
	// caserecordDescUpdatedAt is the schema descriptor for updated_at field.
	caserecordDescUpdatedAt := caserecordFields[5].Descriptor()
	// caserecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	caserecord.DefaultUpdatedAt = caserecordDescUpdatedAt.Default.(func() time.Time)
	// caserecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	caserecord.UpdateDefaultUpdatedAt = caserecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescBody is the schema descriptor for body field.
	commentDescBody := commentFields[0].Descriptor()
	// comment.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	comment.BodyValidator = commentDescBody.Validators[0].(func(string) error)
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[2].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	entityFields := schema.Entity{}.Fields()
	_ = entityFields
	// entityDescValue is the schema descriptor for value field.
	entityDescValue := entityFields[1].Descriptor()
	// entity.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	entity.ValueValidator = entityDescValue.Validators[0].(func(string) error)
	// entityDescConfidence is the schema descriptor for confidence field.
	entityDescConfidence := entityFields[2].Descriptor()
	// entity.DefaultConfidence holds the default value on creation for the confidence field.
	entity.DefaultConfidence = entityDescConfidence.Default.(float64)
	// entityDescCreatedAt is the schema descriptor for created_at field.
	entityDescCreatedAt := entityFields[3].Descriptor()
	// entity.DefaultCreatedAt holds the default value on creation for the created_at field.
	entity.DefaultCreatedAt = entityDescCreatedAt.Default.(func() time.Time)
	evidenceFields := schema.Evidence{}.Fields()
	_ = evidenceFields
	// evidenceDescTitle is the schema descriptor for title field.
	evidenceDescTitle := evidenceFields[1].Descriptor()
	// evidence.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	evidence.TitleValidator = evidenceDescTitle.Validators[0].(func(string) error)
	// evidenceDescCreatedAt is the schema descriptor for created_at field.
	evidenceDescCreatedAt := evidenceFields[11].Descriptor()
	// evidence.DefaultCreatedAt holds the default value on creation for the created_at field.
	evidence.DefaultCreatedAt = evidenceDescCreatedAt.Default.(func() time.Time)
	// evidenceDescUpdatedAt is the schema descriptor for updated_at field.
	evidenceDescUpdatedAt := evidenceFields[12].Descriptor()
	// evidence.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	evidence.DefaultUpdatedAt = evidenceDescUpdatedAt.Default.(func() time.Time)
	// evidence.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	evidence.UpdateDefaultUpdatedAt = evidenceDescUpdatedAt.UpdateDefault.(func() time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[0].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
